import {
  Image,
  Maximize2,
  Minimize2,
  Crop,
  RotateCw,
  RotateCcw,
  FlipHorizontal2,
  Contrast,
  Aperture,
  Stamp,
  Tags,
  SlidersHorizontal,
  Eraser,
  Files,
  Scissors,
  FileMinus,
  FileImage,
  ListOrdered,
  Droplets,
  Droplet,
  FileText,
  Images,
  Download,
  Youtube,
  Music,
  QrCode,
  Braces,
  Hash,
  Wrench,
  PackageOpen,
  LockOpen,
  GripVertical,
  Sparkles,
  Wand2,
  Instagram,
  Video,
  Film,
  Twitter,
  Headphones,
  FileAudio,
  Link2,
  Binary,
  Palette,
  KeyRound,
  Regex,
  FileCode,
  Zap,
  ALargeSmall,

  ArrowLeftRight,
  ArrowUpDown,
  Atom,
  Banknote,
  BookOpen,
  Box,
  Calculator,
  Calendar,
  Clock,
  Code,
  CreditCard,
  Dices,
  Edit3,
  EyeOff,
  FileDigit,
  Filter,
  Fingerprint,
  FunctionSquare,
  GitCompare,
  Grid3x3,
  HardDrive,
  Heart,
  Hourglass,
  Key,
  Languages,
  Lock,
  Magnet,
  Merge,
  Monitor,
  Moon,
  Network,
  PenTool,
  Pilcrow,
  Presentation,
  Radio,
  Receipt,
  Repeat,
  Replace,
  Ruler,
  Scale,
  ScanLine,
  Shapes,
  Shield,
  Sigma,
  Smile,
  Split,
  Square,
  Table,
  Timer,
  Trash2,
  TrendingUp,
  Type,
  Unlock,
  Wallet,
  Wifi,
  ZoomIn,
  LayoutGrid,
  Volume2,
  Globe,
  Server,
  ChartScatter,
  PieChart,
  LineChart,
  BarChart,
  Share2,
  Smartphone,
  type LucideIcon,
  Cpu,
  MonitorPlay,
  CircuitBoard,
  BatteryCharging,
  ScrollText,
  Keyboard,
  Activity,
  Percent,
  Pipette,
  AudioWaveform,
  FileOutput,
  FileArchive,
  AppWindow,
  FolderSearch,
  Table2,
  Layers,
  AlignLeft,
  ArrowDownUp,
  Copy,
  Plus,
  Rows3,
  SplitSquareVertical,
  ShieldCheck,
  ScanText,
  FileSearch,
  FileEdit,
  MonitorUp,
  ClipboardList,
  ImagePlus,
  CopyCheck,
  Sparkle,
  FilePen,
  Maximize,
  Mic2,
  VolumeX,
} from "lucide-react";

import type { ToolCategory } from "@furinakit/shared";

/** Maps a tool's `icon` string (a Lucide name) to the component. */
export const iconMap: Record<string, LucideIcon> = {
  Image,
  Maximize2,
  Minimize2,
  Crop,
  RotateCw,
  RotateCcw,
  FlipHorizontal2,
  Contrast,
  Aperture,
  Stamp,
  Tags,
  SlidersHorizontal,
  Eraser,
  Files,
  Scissors,
  FileMinus,
  FileImage,
  EyeOff,
  FunctionSquare,
  ListOrdered,
  Droplets,
  Droplet,
  FileText,
  Images,
  Download,
  Youtube,
  Music,
  QrCode,
  Braces,
  Hash,
  Wrench,
  PackageOpen,
  LockOpen,
  GripVertical,
  Sparkles,
  Wand2,
  Instagram,
  Video,
  Film,
  Twitter,
  Headphones,
  FileAudio,
  Link2,
  Binary,
  Palette,
  KeyRound,
  Regex,
  FileCode,
  Zap,
  ALargeSmall,
  ArrowLeftRight,
  ArrowUpDown,
  Atom,
  Banknote,
  BookOpen,
  Box,
  Calculator,
  Calendar,
  Clock,
  Code,
  CreditCard,
  Dices,
  Edit3,
  FileDigit,
  Filter,
  Fingerprint,
  GitCompare,
  Grid3x3,
  HardDrive,
  Heart,
  Hourglass,
  Key,
  Languages,
  Lock,
  Magnet,
  Merge,
  Monitor,
  Moon,
  Network,
  PenTool,
  Pilcrow,
  Presentation,
  Radio,
  Receipt,
  Repeat,
  Replace,
  Ruler,
  Scale,
  ScanLine,
  Shapes,
  Shield,
  Sigma,
  Smile,
  Split,
  Square,
  Table,
  Timer,
  Trash2,
  TrendingUp,
  Type,
  Unlock,
  Wallet,
  Wifi,
  ZoomIn,
  LayoutGrid,
  Volume2,
  Globe,
  Server,
  ChartScatter,
  PieChart,
  LineChart,
  BarChart,
  Share2,
  Smartphone,
  "scatter-chart": ChartScatter,

  "pie-chart": PieChart,
  "line-chart": LineChart,
  "bar-chart": BarChart,

  // 系统工具（读取本机硬件与系统信息）
  "sys-overview": Monitor,
  "sys-cpu-memory": Cpu,
  "sys-gpu-display": MonitorPlay,
  "sys-board-bios": CircuitBoard,
  "sys-storage": HardDrive,
  "sys-network": Wifi,
  "sys-power": BatteryCharging,

  // 生活与计算类
  teleprompter: ScrollText,
  "typing-test": Keyboard,
  "body-fat": Activity,
  "interest-calc": Percent,
  "color-extract": Pipette,
  "bpm-detect": AudioWaveform,

  // 演示文稿、PDF 裁边与图标生成
  "ppt-extract-media": Images,
  "ppt-extract-text": FileOutput,
  "ppt-compress": FileArchive,
  "pdf-crop": Crop,
  "app-icon-generator": AppWindow,

  // 占用空间排查（只读）
  "big-file-scan": FolderSearch,

  // AI 工具
  "ai-polish": Wand2,
  "ai-translate": Languages,
  "ai-document": FileText,
  "ai-table": Table2,

  // 文本行处理
  "text-lines": Rows3,
  "css-studio": Palette,
  "encoder-studio": Binary,
  "checksum-studio": ShieldCheck,
  "json-studio": Braces,

  // OCR
  "ocr-image": ScanText,
  "ocr-pdf": FileSearch,
  "screenshot-ocr": MonitorUp,
  "screen-recorder": Video,
  "clipboard-history": ClipboardList,
  "watermark-remove": Eraser,
  "pdf-editor": FileEdit,
  "pdf-content-edit": FilePen,
  "bg-replace": ImagePlus,
  "photo-restore": Sparkle,
  "colorize-photo": Palette,
  "ai-outpaint": Maximize,
  "vocal-separate": Mic2,
  "audio-denoise": VolumeX,
  "image-dedup": CopyCheck,
  "net-query": Globe,};

export function getToolIcon(name: string): LucideIcon {
  return iconMap[name] ?? Wrench;
}

/** Per-category Lucide icon used for section headers, nav, palette groups. */
export const categoryIcon: Record<ToolCategory, LucideIcon> = {
  image: Image,
  download: Video,
  audio: Music,
  pdf: FileText,
  utility: Wrench,
  text: Type,
  mathcalc: Sigma,
  dev: Code,
  security: Shield,
  hardware: Monitor,
  ai: Sparkles,
};
