
import { createUiText as __createUiText, uiMessage as __msg, useLanguage as __useLanguage } from "@/lib/language";
const __ui = __createUiText("components/capture/image-editor.tsx");
import {useEscapeDismiss} from "@/lib/use-escape-dismiss";
import {useEffect,useRef,useState,type PointerEvent} from "react";
import {invoke} from "@tauri-apps/api/core";
import {listen} from "@tauri-apps/api/event";
import {Square, Circle, MoveUpRight, Pencil, Paintbrush, Grid2X2, Crop, RotateCcw, RotateCw, Undo2, ImageOff, X, Check, Download, Move} from "lucide-react";
import {useTheme} from "@/components/theme-provider";
import {ensureOutputDirectory} from "@/lib/output-directory";
import {canvasPoint,cropBetween,validCrop,type Point,type CropRect} from "@/lib/image-edit-geometry";
import {createPortal} from "react-dom";
import "./capture-window.css";
const id=new URLSearchParams(location.search).get("shotId")||"";
const rpc=<T,>(name:string,args:Record<string,unknown>={})=>invoke<T>(name,{id,...args});
type Mode="move"|"rect"|"ellipse"|"arrow"|"pen"|"mosaic"|"text"|"crop";
type Finish="close"|"reset"|null;
function MosaicIcon({size=20,...props}:React.SVGProps<SVGSVGElement>&{size?:number}){
 return <svg viewBox="0 0 24 24" width={size} height={size} fill="none" {...props} aria-hidden="true"><rect x="3" y="3" width="18" height="18" rx="2.5" stroke="currentColor" strokeWidth="1.5"/>{[[4,4,.25],[9.5,4,.75],[15,4,.4],[4,9.5,.85],[9.5,9.5,.35],[15,9.5,.9],[4,15,.4],[9.5,15,.8],[15,15,.25]].map(([x,y,opacity],i)=><rect key={i} x={x} y={y} width="5" height="5" rx=".4" fill="currentColor" opacity={opacity}/>)}</svg>;
}
const tools=[{id:"rect",name:"矩形",icon:Square},{id:"ellipse",name:"椭圆",icon:Circle},{id:"arrow",name:"箭头",icon:MoveUpRight},{id:"pen",name:"画笔",icon:Pencil},{id:"mosaic",name:"马赛克",icon:MosaicIcon},{id:"crop",name:"裁剪",icon:Crop}] as const;
const swatches=["#ef4444","#f59e0b","#facc15","#22c55e","#38bdf8","#8b5cf6","#ffffff","#171717"];
export type EditorHandle={data:()=>string;isDirty:()=>boolean};
export function ImageEditor({inline=false,locked=false,toolbar,onReady,onMode}:{inline?:boolean;locked?:boolean;toolbar?:HTMLElement|null;onReady?:(h:EditorHandle)=>void;onMode?:(moving:boolean)=>void}){
  const __locale = __useLanguage();
 const {colors}=useTheme();
 const canvas=useRef<HTMLCanvasElement>(null),preview=useRef<HTMLCanvasElement>(null),wrap=useRef<HTMLDivElement>(null);
 const original=useRef(""),applied=useRef(""),current=useRef(""),dirty=useRef(false),lock=useRef(false);
 const [history,setHistory]=useState<string[]>([]),[index,setIndex]=useState(0),[ready,setReady]=useState(false),[busy,setBusy]=useState(false);
 const [size,setSize]=useState({width:1,height:1}),[mode,setMode]=useState<Mode>(inline?"move":"crop"),[color,setColor]=useState(swatches[0]),[width,setWidth]=useState(4),[font,setFont]=useState(28);
 const [crop,setCrop]=useState<CropRect|null>(null),[ratio,setRatio]=useState(0),[pattern,setPattern]=useState("pixel"),[brushSize,setBrushSize]=useState(36);
 const [text,setText]=useState<{x:number;y:number;value:string}|null>(null),[scale,setScale]=useState(1),[cursor,setCursor]=useState<Point|null>(null);
 const [notice,setNotice]=useState(""),[confirm,setConfirm]=useState<Finish>(null);
 const start=useRef<Point|null>(null),last=useRef<Point|null>(null),gesture=useRef(false),mosaic=useRef<HTMLCanvasElement|null>(null);
 const close=()=>{if(inline)return;if(lock.current)return;if(dirty.current||text?.value.trim())setConfirm("close");else void rpc("shot_window",{operation:"close"}).catch(e=>setNotice(String(e)));};
 const closeRef=useRef(close);closeRef.current=close;
 useEscapeDismiss(()=>{if(confirm)setConfirm(null);else if(text)setText(null);else close();},!inline||!!confirm,50);
 useEffect(()=>{let alive=true,off:(()=>void)|undefined;void listen("shot-close-requested",()=>closeRef.current()).then(fn=>{if(alive)off=fn;else fn();});void rpc<{dataUrl:string}>("shot_get").then(s=>{if(alive){original.current=applied.current=s.dataUrl;setHistory([s.dataUrl]);}}).catch(e=>{if(alive)setNotice(String(e));});return()=>{alive=false;off?.();};},[]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(""),5000);return()=>clearTimeout(t);},[notice]);
 const source=history[index];
 useEffect(()=>{if(!source)return;let alive=true;setReady(false);const img=new Image();img.onload=()=>{if(!alive||!canvas.current||!preview.current)return;const c=canvas.current;c.width=preview.current.width=img.width;c.height=preview.current.height=img.height;c.getContext("2d")!.drawImage(img,0,0);current.current=source;dirty.current=source!==applied.current;setSize({width:img.width,height:img.height});setCrop(null);setReady(true);};img.onerror=()=>{if(alive)setNotice("图片无法载入");};img.src=source;return()=>{alive=false;};},[source]);
 useEffect(()=>{const update=()=>setScale((canvas.current?.getBoundingClientRect().width||size.width)/size.width);const ro=new ResizeObserver(update);if(wrap.current)ro.observe(wrap.current);update();return()=>ro.disconnect();},[size]);
 const commit=(c:HTMLCanvasElement)=>{const url=c.toDataURL("image/png");if(url===current.current)return;const next=[...history.slice(0,index+1),url];while(next.length>13||(next.length>1&&next.reduce((n,s)=>n+s.length,0)>64*1024*1024))next.shift();current.current=url;dirty.current=url!==applied.current;setReady(false);setHistory(next);setIndex(next.length-1);setCrop(null);preview.current?.getContext("2d")?.clearRect(0,0,size.width,size.height);};
 const finishText=()=>{if(!text||!canvas.current)return;const value=text.value.trimEnd();setText(null);if(!value.trim())return;const ctx=canvas.current.getContext("2d")!;ctx.font=`${font}px "Segoe UI","Microsoft YaHei",sans-serif`;ctx.textBaseline="top";ctx.fillStyle=color;value.split("\n").forEach((line,i)=>ctx.fillText(line,text.x,text.y+i*font*1.35));commit(canvas.current);};
 const point=(e:PointerEvent<HTMLCanvasElement>)=>canvasPoint({x:e.clientX,y:e.clientY},e.currentTarget.getBoundingClientRect(),e.currentTarget.width,e.currentTarget.height);
 const makeMosaic=(c:HTMLCanvasElement)=>{const layer=document.createElement("canvas");layer.width=c.width;layer.height=c.height;const ctx=layer.getContext("2d")!;
  if(pattern==="pixel"){const small=document.createElement("canvas");small.width=Math.max(1,Math.ceil(c.width/14));small.height=Math.max(1,Math.ceil(c.height/14));small.getContext("2d")!.drawImage(c,0,0,small.width,small.height);ctx.imageSmoothingEnabled=false;ctx.drawImage(small,0,0,c.width,c.height);}
  else if(pattern==="blur"){ctx.filter="blur(14px)";ctx.drawImage(c,0,0);}
  else if(pattern==="ink"){ctx.fillStyle="#34383d";ctx.fillRect(0,0,c.width,c.height);}
  else {const g=ctx.createLinearGradient(0,0,c.width,c.height);g.addColorStop(0,pattern==="frost"?"#b5a4eb":"#a7a8ac");g.addColorStop(1,pattern==="frost"?"#c1e4f0":"#ecebea");ctx.fillStyle=g;ctx.fillRect(0,0,c.width,c.height);for(let y=0;y<c.height;y+=24)for(let x=0;x<c.width;x+=24){const v=((x*13+y*7)%97)/97;ctx.fillStyle=`rgba(255,255,255,${.15+v*.4})`;ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x+24,y+5+v*19);ctx.lineTo(x+v*20,y+24);ctx.closePath();ctx.fill();}}
  mosaic.current=layer;
 };
 const stamp=(p:Point)=>{const c=canvas.current;if(!c||!mosaic.current)return;const ctx=c.getContext("2d")!;ctx.save();ctx.beginPath();ctx.arc(p.x,p.y,brushSize/2,0,Math.PI*2);ctx.clip();ctx.drawImage(mosaic.current,0,0);ctx.restore();};
 const draw=(p:Point,shift=false)=>{if(!gesture.current||!start.current||!canvas.current)return;const a=start.current,c=canvas.current;
  if(mode==="mosaic"){const prev=last.current||p,n=Math.max(1,Math.ceil(Math.hypot(p.x-prev.x,p.y-prev.y)/Math.max(1,brushSize/6)));for(let i=1;i<=n;i++)stamp({x:prev.x+(p.x-prev.x)*i/n,y:prev.y+(p.y-prev.y)*i/n});last.current=p;return;}
  if(mode==="pen"){const ctx=c.getContext("2d")!;ctx.lineTo(p.x,p.y);ctx.stroke();return;}
  if(mode==="crop"){if(!ratio){setCrop(cropBetween(a,p,size.width,size.height));return;}const sx=p.x<a.x?-1:1,sy=p.y<a.y?-1:1;let w=Math.max(Math.abs(p.x-a.x),Math.abs(p.y-a.y)*ratio),h=w/ratio;const f=Math.min(1,(sx<0?a.x:size.width-a.x)/Math.max(w,1),(sy<0?a.y:size.height-a.y)/Math.max(h,1));w*=f;h*=f;setCrop(cropBetween(a,{x:a.x+sx*w,y:a.y+sy*h},size.width,size.height));return;}
  const ctx=preview.current!.getContext("2d")!;ctx.clearRect(0,0,c.width,c.height);ctx.strokeStyle=ctx.fillStyle=color;ctx.lineWidth=width;ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();
  if(mode==="arrow"){const distance=Math.hypot(p.x-a.x,p.y-a.y);if(distance<2)return;let angle=Math.atan2(p.y-a.y,p.x-a.x);if(shift)angle=Math.round(angle/(Math.PI/4))*Math.PI/4;const ux=Math.cos(angle),uy=Math.sin(angle),head=Math.min(distance*.48,Math.max(14,width*4.5)),neck=distance-head;const pt=(along:number,side:number)=>[a.x+ux*along-uy*side,a.y+uy*along+ux*side];const points=[pt(0,-width*.22),pt(neck,-width*.65),pt(neck,-head*.42),pt(distance,0),pt(neck,head*.42),pt(neck,width*.65),pt(0,width*.22)];ctx.moveTo(points[0][0],points[0][1]);points.slice(1).forEach(q=>ctx.lineTo(q[0],q[1]));ctx.closePath();ctx.fill();}
  else {const x=Math.min(a.x,p.x),y=Math.min(a.y,p.y),w=Math.abs(p.x-a.x),h=Math.abs(p.y-a.y);if(mode==="rect")ctx.strokeRect(x,y,w,h);else if(mode==="ellipse"){ctx.ellipse(x+w/2,y+h/2,w/2,h/2,0,0,Math.PI*2);ctx.stroke();}}
 };
 const down=(e:PointerEvent<HTMLCanvasElement>)=>{if(mode==="move"||!ready||busy||locked||gesture.current||e.button!==0)return;e.preventDefault();const p=point(e),ctx=e.currentTarget.getContext("2d")!;if(text){finishText();return;}if(mode==="text"){setText({x:Math.min(p.x,Math.max(0,size.width-font*2)),y:Math.min(p.y,Math.max(0,size.height-font*1.5)),value:""});return;}e.currentTarget.setPointerCapture(e.pointerId);start.current=last.current=p;gesture.current=true;setCrop(null);if(mode==="pen"){ctx.strokeStyle=ctx.fillStyle=color;ctx.lineWidth=width;ctx.lineCap=ctx.lineJoin="round";ctx.beginPath();ctx.arc(p.x,p.y,width/2,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.moveTo(p.x,p.y);}if(mode==="mosaic"){makeMosaic(e.currentTarget);stamp(p);}};
 const move=(e:PointerEvent<HTMLCanvasElement>)=>{if(mode==="move")return;const p=point(e);setCursor(mode==="mosaic"?p:null);draw(p,e.shiftKey);};
 const up=(e:PointerEvent<HTMLCanvasElement>)=>{if(!gesture.current)return;draw(point(e),e.shiftKey);gesture.current=false;start.current=null;if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);if(mode!=="crop"){if(["rect","ellipse","arrow"].includes(mode))e.currentTarget.getContext("2d")!.drawImage(preview.current!,0,0);commit(e.currentTarget);}mosaic.current=null;};
 const cancel=()=>{gesture.current=false;start.current=null;setCrop(null);preview.current?.getContext("2d")?.clearRect(0,0,size.width,size.height);const img=new Image();const before=current.current;img.onload=()=>{if(current.current===before)canvas.current?.getContext("2d")?.drawImage(img,0,0);};img.src=before;};
 const rotate=(right:boolean)=>{if(!ready||busy||text)return;const old=canvas.current!,c=document.createElement("canvas");c.width=old.height;c.height=old.width;const ctx=c.getContext("2d")!;ctx.translate(right?c.width:0,right?0:c.height);ctx.rotate((right?1:-1)*Math.PI/2);ctx.drawImage(old,0,0);commit(c);};
 const applyCrop=()=>{if(!canvas.current||!crop||!validCrop(crop))return;const c=document.createElement("canvas");c.width=crop.width;c.height=crop.height;c.getContext("2d")!.drawImage(canvas.current,crop.x,crop.y,crop.width,crop.height,0,0,c.width,c.height);commit(c);};
 const apply=async(save:boolean)=>{if(lock.current||!ready)return;if(text){finishText();return;}if(crop&&validCrop(crop)){setNotice("请先应用裁剪，或切换工具取消选区");return;}lock.current=true;setBusy(true);try{if(save){await ensureOutputDirectory();if(await rpc<boolean>("shot_save",{dataUrl:current.current}))setNotice("PNG 已保存");}else{await rpc("shot_update",{dataUrl:current.current});applied.current=current.current;dirty.current=false;setNotice("已应用到贴图");}}catch(e){setNotice(String(e));}finally{lock.current=false;setBusy(false);}};
 const changeMode=(m:Mode)=>{if(text)finishText();setMode(m);setCrop(null);setNotice("");setCursor(null);};
 useEffect(()=>{onMode?.(mode==="move");},[mode]);
 const data=()=>{if(text)finishText();if(crop&&validCrop(crop))applyCrop();return current.current;};
 useEffect(()=>{onReady?.({data,isDirty:()=>dirty.current||!!text?.value.trim()});});
 const disabled=!ready||busy||locked;
 const themeStyle={"--editor-bg":colors.bg,"--editor-card":colors.card,"--editor-border":colors.borderSolid,"--editor-ink":colors.text,"--editor-muted":colors.muted,"--editor-accent":colors.blue} as React.CSSProperties;
 const editorTools=<>
  <div className="capture-toolbar" role="toolbar" aria-label={__ui("图片编辑工具")}>{inline&&<button className="editor-icon" title={__ui("移动贴图")} aria-label={__ui("移动贴图")} aria-pressed={mode==="move"} onClick={()=>changeMode("move")}><Move size={21} strokeWidth={1.65}/></button>}{tools.slice(0,5).map(t=><button key={t.id} className="editor-icon" title={t.name} aria-label={t.name} aria-pressed={mode===t.id} disabled={disabled} onClick={()=>changeMode(t.id)}><t.icon size={23} strokeWidth={1.8}/></button>)}<button className="editor-icon editor-text-icon" title={__ui("文字")} aria-label={__ui("文字")} aria-pressed={mode==="text"} disabled={disabled} onClick={()=>changeMode("text")}>T</button><button className="editor-icon" title={__ui("裁剪")} aria-label={__ui("裁剪")} aria-pressed={mode==="crop"} disabled={disabled} onClick={()=>changeMode("crop")}><Crop size={23}/></button><i className="editor-divider"/><button className="editor-icon" title={__ui("向左旋转")} aria-label={__ui("向左旋转")} disabled={disabled||!!text} onClick={()=>rotate(false)}><RotateCcw size={22}/></button><button className="editor-icon" title={__ui("向右旋转")} aria-label={__ui("向右旋转")} disabled={disabled||!!text} onClick={()=>rotate(true)}><RotateCw size={22}/></button><button className="editor-icon" title={__ui("撤销")} aria-label={__ui("撤销")} disabled={disabled||index===0||!!text} onClick={()=>setIndex(i=>i-1)}><Undo2 size={22}/></button><button title={__ui("清除编辑，恢复最初原图")} disabled={disabled} onClick={()=>setConfirm("reset")}><ImageOff size={16}/>{__ui("还原原图")}</button></div>
  <div className="capture-toolbar capture-options" style={mode==="move"?{display:"none"}:undefined}>
   {mode==="crop"?<><div className="editor-presets">{[["自由",0],["1:1",1],["3:4",.75],["4:3",4/3],["9:16",9/16],["16:9",16/9]].map(([name,r])=><button key={name} aria-pressed={ratio===r} onClick={()=>{setRatio(Number(r));setCrop(null);}} disabled={disabled}><span className="ratio-glyph" style={{aspectRatio:r||1.25}}/>{__msg(name)}</button>)}</div><button className="primary" disabled={disabled||!crop||!validCrop(crop)} onClick={applyCrop}><Check size={16}/>{__ui("应用裁剪")}</button></>:mode==="mosaic"?<><div className="editor-presets">{[["pixel","像素"],["blur","柔化"],["ink","涂抹"],["frost","星雾"],["foil","银箔"]].map(([v,label])=><button title={__ui(label)} aria-label={__ui(label)} key={v} aria-pressed={pattern===v} disabled={disabled} onClick={()=>setPattern(v)}><span className={`mosaic-swatch ${v}`}/><small>{__ui(label)}</small></button>)}</div><label>{__ui("笔刷")}<input type="range" min="12" max="140" value={brushSize} onChange={e=>setBrushSize(+e.target.value)}/><span>{brushSize}</span></label></>:<><div className="editor-colors">{swatches.map(c=><button key={c} title={c} aria-label={__msg("选择颜色 {0}", c)} aria-pressed={color===c} style={{background:c}} onClick={()=>setColor(c)}/>)}<input aria-label={__ui("自定义颜色")} title={__ui("自定义颜色")} type="color" value={color} onChange={e=>setColor(e.target.value)}/></div><label>{mode==="text"?__ui("字号"):__ui("笔宽")}<input type="range" min={mode==="text"?12:1} max={mode==="text"?120:24} value={mode==="text"?font:width} onChange={e=>mode==="text"?setFont(+e.target.value):setWidth(+e.target.value)}/><span>{mode==="text"?font:width}</span></label>{text&&<button className="primary" onClick={finishText}><Check size={16}/>{__ui("完成文字")}</button>}</>}
  </div>
 </>;
 return <main className={`capture-window ${inline?"pin-inline-editor":""}`} style={themeStyle}>
  {!inline&&<header className="capture-title"><strong>{__ui("图片编辑")}</strong><span>{size.width} × {size.height}</span><button title={__ui("关闭编辑器")} aria-label={__ui("关闭编辑器")} disabled={busy} onClick={close}><X size={18}/></button></header>}
  {inline?(toolbar?createPortal(<div className="pin-editor-tools capture-window" style={themeStyle}>{editorTools}</div>,toolbar):null):editorTools}
  <div className="capture-stage"><div ref={wrap} className="capture-canvas-wrap" style={{width:inline?"100%":size.width}}><canvas ref={canvas} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel} onPointerLeave={()=>{if(!gesture.current)setCursor(null);}} style={{cursor:mode==="move"?"move":mode==="text"?"text":mode==="mosaic"?"none":"crosshair"}} aria-label={__ui("图片编辑画布")}/><canvas className="capture-draft" ref={preview}/>{crop&&<svg viewBox={`0 0 ${size.width} ${size.height}`}><rect x={crop.x} y={crop.y} width={crop.width} height={crop.height} fill="#ffffff12" stroke="#38bdf8" strokeWidth="2" vectorEffect="non-scaling-stroke" strokeDasharray="6 3"/></svg>}{mode==="mosaic"&&cursor&&<span className="capture-brush" style={{left:`${cursor.x/size.width*100}%`,top:`${cursor.y/size.height*100}%`,width:brushSize*scale,height:brushSize*scale}}><Paintbrush size={16}/></span>}{text&&<textarea disabled={locked||busy} autoFocus rows={1} wrap="off" className="capture-inline-text" aria-label={__ui("在图片中输入文字")} placeholder="" value={text.value} maxLength={1000} onChange={e=>setText({...text,value:e.target.value})} onKeyDown={e=>{if(e.key==="Escape"){e.preventDefault();e.stopPropagation();setText(null);}else if(e.key==="Enter"&&(e.ctrlKey||e.metaKey)){e.preventDefault();finishText();}}} style={{left:`${text.x/size.width*100}%`,top:`${text.y/size.height*100}%`,color,fontSize:font*scale,lineHeight:1.35,width:Math.max(16,Math.min((size.width-text.x)*scale-4,Math.max(font*.6,...text.value.split("\n").map(line=>{const ctx=canvas.current?.getContext("2d");if(!ctx)return line.length*font;ctx.font=`${font}px "Segoe UI","Microsoft YaHei",sans-serif`;return ctx.measureText(line).width;}))*scale+8)),height:Math.max(font*scale*1.35,Math.min((size.height-text.y)*scale-2,text.value.split("\n").length*font*scale*1.35+4)),minWidth:0,minHeight:0,padding:0,margin:0,resize:"none",overflow:"hidden",background:"transparent",border:"1px dashed #22c55e",borderRadius:0,boxShadow:"none",boxSizing:"content-box"}}/>}</div></div>
  {!inline&&<footer className="capture-footer"><div/ ><div><button disabled={disabled} onClick={()=>void apply(true)}><Download size={16}/>{__ui("另存 PNG")}</button><button className="primary" disabled={disabled} onClick={()=>void apply(false)}><Check size={16}/>{__ui("应用到贴图")}</button></div></footer>}
  {!inline&&notice&&<div role="status" className="capture-notice">{__msg(notice)}<button aria-label={__ui("关闭提示")} onClick={()=>setNotice("")}><X size={13}/></button></div>}
  {confirm&&<div className="capture-modal"><section role="dialog" aria-modal="true" aria-label={confirm==="reset"?__ui("还原原图"):__ui("关闭编辑器")}><strong>{confirm==="reset"?__ui("还原最初的图片？"):__ui("还有未应用的编辑")}</strong><p>{confirm==="reset"?__ui("将清除当前标注、文字和裁剪。原文件不会被改动。"):__ui("可以返回后先应用到贴图或另存 PNG。")}</p><div><button autoFocus onClick={()=>setConfirm(null)}>{__ui("继续编辑")}</button><button className="primary" onClick={()=>{if(confirm==="reset"){setText(null);setHistory([original.current]);setIndex(0);setCrop(null);dirty.current=original.current!==applied.current;setConfirm(null);}else void rpc("shot_window",{operation:"close"}).catch(e=>setNotice(String(e)));}}>{confirm==="reset"?__ui("还原原图"):__ui("放弃并关闭")}</button></div></section></div>}
 </main>;
}
