"use client";
import { createUiText as __createUiText, uiMessage as __msg, useLanguage as __useLanguage } from "@/lib/language";
const __ui = __createUiText("components/tools/magnet-download-tool.tsx");

import { useEffect, useRef, useState, useCallback } from "react";
import { Magnet, Download, FolderOpen, ClipboardPaste, Sparkles, Loader2, Pause, Play, Square, FileUp, RefreshCw, ShieldCheck, AlertCircle, Trash2 } from "lucide-react";
import { Button, ProgressBar } from "@/components/ui/primitives";
import { useToast } from "@/components/ui/toast";
import { ensureOutputDirectory } from "@/lib/output-directory";
import { isMagnetTorrentInfo, type MagnetTorrentInfo } from "@/lib/magnet-info";
interface Task { id:string; toolId:string; nativeEngine:string; status:string; progress:number; message?:string; error?:string; outputDir?:string; downloadedBytes?:number; totalBytes?:number; speed?:number; connections?:number; seeders?:number; createdAt?:string }
const labels:Record<string,string>={pending:"等待启动",processing:"下载中",stopping:"正在停止",paused:"已暂停",completed:"已完成",failed:"失败",cancelled:"已取消"};
const bytes=(n=0)=>n<1024?`${n} B`:n<1048576?`${(n/1024).toFixed(1)} KB`:n<1073741824?`${(n/1048576).toFixed(1)} MB`:`${(n/1073741824).toFixed(2)} GB`;
const active=(s:string)=>["pending","processing","stopping"].includes(s);
export function MagnetDownloadTool(){
  const __locale = __useLanguage();
 const {toast}=useToast();const [uri,setUri]=useState("");const [torrent,setTorrent]=useState<File|null>(null);const [info,setInfo]=useState<MagnetTorrentInfo|null>(null);const [tasks,setTasks]=useState<Task[]>([]);const [ready,setReady]=useState(false);const [error,setError]=useState("");const [busy,setBusy]=useState("");const [parsing,setParsing]=useState(false);
 const mounted=useRef(false);const locked=useRef(false);const loading=useRef(false);const parseEpoch=useRef(0);const fileInput=useRef<HTMLInputElement>(null);
 const reload=useCallback(async()=>{if(loading.current)return;loading.current=true;try{const response=await fetch("/api/magnet-download?action=status",{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error||"无法读取下载任务");if(!mounted.current)return;setReady(data.ready===true);setTasks(Array.isArray(data.tasks)?data.tasks.filter((t:Task)=>t?.nativeEngine==="aria2"&&/^[a-f0-9-]{1,64}$/i.test(t.id)):[]);setError(data.ready?"":data.message||"完整安装包中缺少aria2引擎");}catch(e){if(mounted.current)setError(e instanceof Error?e.message:"任务读取失败");}finally{loading.current=false;}},[]);
 useEffect(()=>{mounted.current=true;void reload();const timer=setInterval(()=>void reload(),1400);return()=>{mounted.current=false;parseEpoch.current++;clearInterval(timer);};},[reload]);
 const pick=(file:File|undefined)=>{if(!file)return;if(!file.name.toLowerCase().endsWith(".torrent")||file.size===0||file.size>8*1024*1024){toast({title:"请选择不超过8MB的有效torrent文件",variant:"error"});return;}parseEpoch.current++;setTorrent(file);setUri("");setInfo(null);setParsing(false);};
 const parse=async()=>{const epoch=++parseEpoch.current;setParsing(true);try{let body:BodyInit;let headers:HeadersInit|undefined;if(torrent){const form=new FormData();form.append("file",torrent);body=form;}else{body=JSON.stringify({url:uri.trim()});headers={"Content-Type":"application/json"};}const response=await fetch("/api/magnet-info",{method:"POST",body,headers});const data=await response.json();if(!response.ok||!isMagnetTorrentInfo(data))throw new Error(data.error||"无法解析此链接或种子");if(mounted.current&&epoch===parseEpoch.current)setInfo(data);}catch(e){if(mounted.current&&epoch===parseEpoch.current)toast({title:"解析失败",description:e instanceof Error?e.message:"",variant:"error"});}finally{if(mounted.current&&epoch===parseEpoch.current)setParsing(false);}};
 const act=async(action:string,job?:string)=>{if(action==="delete"&&!window.confirm(__ui("删除这条任务记录？已下载文件和断点文件将保留，不会删除磁盘文件。")))return;if(locked.current)return;locked.current=true;setBusy(job||"start");try{let body:BodyInit;let headers:HeadersInit|undefined;if(action==="start"){await ensureOutputDirectory();const form=new FormData();form.append("action","start");if(torrent)form.append("file",torrent);else form.append("magnet",uri.trim());body=form;}else{body=JSON.stringify({action,job});headers={"Content-Type":"application/json"};}const response=await fetch("/api/magnet-download",{method:"POST",body,headers});const data=await response.json();if(!response.ok||data.ok!==true)throw new Error(data.error||"操作失败");window.dispatchEvent(new Event("furinakit:jobs-updated"));if(mounted.current){await reload();if(action==="start")toast({title:"真实下载任务已创建",description:"关闭此页面不影响下载；退出软件会停止自有引擎并保留断点。",variant:"success"});}}catch(e){if(mounted.current)toast({title:"操作失败",description:e instanceof Error?e.message:"",variant:"error"});}finally{locked.current=false;if(mounted.current)setBusy("");}};
 return <div className="flex flex-col gap-4">
  <section className="rounded-2xl border border-border bg-card p-5">
   <header className="mb-4 flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><Magnet size={21}/></span><div><h2 className="text-base font-semibold">{__ui("磁力与种子下载")}</h2><p className="mt-0.5 text-xs text-muted-foreground">{__ui("内置 aria2 · 真实进度 · 断点保留")}</p></div><span className="ml-auto rounded-full bg-secondary px-3 py-1 text-xs">{ready?__ui("引擎已打包"):__ui("检查引擎中")}</span></header>
   <textarea value={uri} onChange={e=>{parseEpoch.current++;setUri(e.target.value);setTorrent(null);setInfo(null);setParsing(false);}} placeholder={__ui("粘贴 magnet:?xt=urn:btih:…")} rows={3} className="w-full resize-y rounded-xl border border-border bg-background p-3 text-sm outline-none focus:ring-2 focus:ring-primary/20"/>
   <div className="mt-3 flex flex-wrap items-center gap-2" data-furinakit-file-field>
    <input ref={fileInput} type="file" accept=".torrent" className="sr-only" onChange={e=>{pick(e.currentTarget.files?.[0]);e.currentTarget.value="";}}/>
    <Button variant="outline" size="sm" onClick={()=>fileInput.current?.click()}><FileUp size={14}/>{__ui("选择种子")}</Button>
    <Button variant="ghost" size="sm" onClick={async()=>{try{const text=await navigator.clipboard.readText();if(mounted.current){parseEpoch.current++;setUri(text.trim());setTorrent(null);setInfo(null);}}catch{toast({title:"请手动粘贴磁力链接",variant:"info"});}}}><ClipboardPaste size={14}/>{__ui("粘贴")}</Button>
     <Button variant="ghost" size="sm" onClick={()=>{parseEpoch.current++;setUri("magnet:?xt=urn:btih:dd8255ecdc7ca55fb0bbf81323d87062db1f6d1c&dn=Big+Buck+Bunny");setTorrent(null);setInfo(null);}}><Sparkles size={14}/>{__ui("填入示例")}</Button>
    <Button variant="ghost" size="sm" disabled={parsing||(!torrent&&!uri.trim())} onClick={()=>void parse()}>{parsing?<Loader2 size={14} className="animate-spin"/>:<ShieldCheck size={14}/>}{__ui("仅解析（不联网）")}</Button>
    <Button className="ml-auto" disabled={!ready||!!busy||(!torrent&&!uri.trim())} onClick={()=>void act("start")}>{busy==="start"?<Loader2 size={15} className="animate-spin"/>:<Download size={15}/>}{__ui("联网开始下载")}</Button>
   </div>
   {torrent&&<p className="mt-3 truncate text-xs text-primary">{__ui("已选择：")}{torrent.name} · {bytes(torrent.size)}{__ui("（可拖入其它种子替换）")}</p>}
   {info&&<div className="mt-3 rounded-xl bg-secondary/60 p-3 text-xs leading-6"><p className="font-medium">{info.name}</p><p className="break-all text-muted-foreground">BTIH：{info.infoHash}</p><p>{info.metadataResolved?__msg("{0} · {1}个文件", info.sizeText, info.fileCount ?? __ui("未知")) : __ui("仅解析了链接结构；下载开始后由实际节点提供大小与文件信息。")}</p>{info.files&&<details><summary className="cursor-pointer">{__ui("文件列表")}</summary><div className="max-h-40 overflow-auto">{info.files.map((f,i)=><p key={i} className="break-all">{f.path} · {f.sizeText}</p>)}</div></details>}</div>}
   <p className="mt-3 text-[11px] leading-5 text-muted-foreground">{__ui("文件直接写入默认输出目录中的独立任务文件夹，不覆盖同名文件。最多同时下载3个任务。下载会连接公开节点；请仅下载你有权获取的内容。完成后不持续做种。下载不限速；实际速度取决于可用做种者、对端上传与网络，连接数不等于有效供给。")}</p>
  </section>
  {error&&<div role="alert" className="flex items-start gap-2 rounded-xl border border-destructive/20 bg-destructive/5 p-3 text-xs text-destructive"><AlertCircle size={15} className="shrink-0"/>{__msg(error)}</div>}
  <section className="rounded-2xl border border-border bg-card p-4"><header className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-semibold">{__ui("下载任务")}</h3><p className="mt-1 text-[11px] text-muted-foreground">{__ui("任务记录持久保存；重新打开软件后需手动继续，不会自行联网。显示最近100条。")}</p></div><Button size="sm" variant="ghost" onClick={()=>void reload()} aria-label={__ui("刷新任务")}><RefreshCw size={14}/></Button></header>
   {!tasks.length&&<div className="rounded-xl border border-dashed border-border py-9 text-center text-xs text-muted-foreground">{__ui("还没有下载任务，粘贴链接或拖入种子开始。")}</div>}
   <div className="space-y-3">{tasks.slice(0,100).map(task=><article key={task.id} className="rounded-xl border border-border bg-background/50 p-3.5">
    <div className="flex flex-wrap items-center justify-between gap-2"><p className="text-xs font-semibold">{__ui(labels[task.status])||__msg(task.status)}<span className="ml-2 font-normal text-muted-foreground">{task.createdAt?new Date(task.createdAt).toLocaleString():task.id.slice(0,8)}</span></p><span className="font-mono text-xs text-muted-foreground">{bytes(task.downloadedBytes)} / {task.totalBytes?bytes(task.totalBytes):__ui("获取元数据")}</span></div>
    <div className="my-2.5"><ProgressBar value={Math.max(0,Math.min(100,task.progress||0))}/></div>
    <p className="text-[11px] leading-5 text-muted-foreground">{__msg(task.message)}{task.status==="processing"&&__msg(" · {0}/s · {1} 个连接 · {task.seeders||0} 个做种者", bytes(task.speed), task.connections || 0)}</p>
    {task.error&&<p className="mt-1 break-words text-xs text-destructive">{__msg(task.error)}</p>}
    <div className="mt-2 flex flex-wrap items-center gap-1.5">{active(task.status)&&<><Button size="sm" variant="outline" disabled={!!busy||task.status==="stopping"} onClick={()=>void act("pause",task.id)}><Pause size={12}/>{__ui("暂停")}</Button><Button size="sm" variant="ghost" disabled={!!busy||task.status==="stopping"} onClick={()=>void act("cancel",task.id)}><Square size={12}/>{__ui("取消")}</Button></>}{task.status==="paused"&&<><Button size="sm" disabled={!!busy||!ready} onClick={()=>void act("resume",task.id)}><Play size={12}/>{__ui("继续下载")}</Button><Button size="sm" variant="ghost" disabled={!!busy} onClick={()=>void act("cancel",task.id)}>{__ui("取消任务")}</Button></>}{task.outputDir&&<Button size="sm" variant="ghost" disabled={!!busy} onClick={()=>void act("open",task.id)}><FolderOpen size={13}/>{__ui("打开下载目录")}</Button>}{["completed","failed","cancelled"].includes(task.status)&&<Button size="sm" variant="ghost" disabled={!!busy} onClick={()=>void act("delete",task.id)}><Trash2 size={13}/>{__ui("删除记录")}</Button>}{busy===task.id&&<Loader2 size={13} className="animate-spin text-muted-foreground"/>}</div>
    {task.outputDir&&<p className="mt-2 truncate text-[10px] text-muted-foreground" title={task.outputDir}>{task.outputDir.replace(/^\\\\\?\\/, "")}</p>}
   </article>)}</div>
  </section>
 </div>;
}
